spring:
  application:
    name:yunifanpage
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

server:
  port: 80